use winit::keyboard::KeyCode;

pub fn keycode_to_sdl_scancode(code: KeyCode) -> Option<u16> {
    use sdl3::keyboard::Scancode;

    let sc = match code {
        KeyCode::KeyA => Scancode::A,
        KeyCode::KeyB => Scancode::B,
        KeyCode::KeyC => Scancode::C,
        KeyCode::KeyD => Scancode::D,
        KeyCode::KeyE => Scancode::E,
        KeyCode::KeyF => Scancode::F,
        KeyCode::KeyG => Scancode::G,
        KeyCode::KeyH => Scancode::H,
        KeyCode::KeyI => Scancode::I,
        KeyCode::KeyJ => Scancode::J,
        KeyCode::KeyK => Scancode::K,
        KeyCode::KeyL => Scancode::L,
        KeyCode::KeyM => Scancode::M,
        KeyCode::KeyN => Scancode::N,
        KeyCode::KeyO => Scancode::O,
        KeyCode::KeyP => Scancode::P,
        KeyCode::KeyQ => Scancode::Q,
        KeyCode::KeyR => Scancode::R,
        KeyCode::KeyS => Scancode::S,
        KeyCode::KeyT => Scancode::T,
        KeyCode::KeyU => Scancode::U,
        KeyCode::KeyV => Scancode::V,
        KeyCode::KeyW => Scancode::W,
        KeyCode::KeyX => Scancode::X,
        KeyCode::KeyY => Scancode::Y,
        KeyCode::KeyZ => Scancode::Z,

        KeyCode::Digit1 => Scancode::_1,
        KeyCode::Digit2 => Scancode::_2,
        KeyCode::Digit3 => Scancode::_3,
        KeyCode::Digit4 => Scancode::_4,
        KeyCode::Digit5 => Scancode::_5,
        KeyCode::Digit6 => Scancode::_6,
        KeyCode::Digit7 => Scancode::_7,
        KeyCode::Digit8 => Scancode::_8,
        KeyCode::Digit9 => Scancode::_9,
        KeyCode::Digit0 => Scancode::_0,

        KeyCode::Escape => Scancode::Escape,
        KeyCode::Enter => Scancode::Return,
        KeyCode::Tab => Scancode::Tab,
        KeyCode::Space => Scancode::Space,
        KeyCode::Backspace => Scancode::Backspace,

        KeyCode::ShiftLeft => Scancode::LShift,
        KeyCode::ShiftRight => Scancode::RShift,
        KeyCode::ControlLeft => Scancode::LCtrl,
        KeyCode::ControlRight => Scancode::RCtrl,
        KeyCode::AltLeft => Scancode::LAlt,
        KeyCode::AltRight => Scancode::RAlt,
        KeyCode::SuperLeft => Scancode::LGui,
        KeyCode::SuperRight => Scancode::RGui,

        KeyCode::ArrowUp => Scancode::Up,
        KeyCode::ArrowDown => Scancode::Down,
        KeyCode::ArrowLeft => Scancode::Left,
        KeyCode::ArrowRight => Scancode::Right,
        KeyCode::Home => Scancode::Home,
        KeyCode::End => Scancode::End,
        KeyCode::PageUp => Scancode::PageUp,
        KeyCode::PageDown => Scancode::PageDown,
        KeyCode::Insert => Scancode::Insert,
        KeyCode::Delete => Scancode::Delete,

        KeyCode::Minus => Scancode::Minus,
        KeyCode::Equal => Scancode::Equals,
        KeyCode::BracketLeft => Scancode::LeftBracket,
        KeyCode::BracketRight => Scancode::RightBracket,
        KeyCode::Backslash => Scancode::Backslash,
        KeyCode::Semicolon => Scancode::Semicolon,
        KeyCode::Quote => Scancode::Apostrophe,
        KeyCode::Comma => Scancode::Comma,
        KeyCode::Period => Scancode::Period,
        KeyCode::Slash => Scancode::Slash,
        KeyCode::Backquote => Scancode::Grave,

        KeyCode::F1 => Scancode::F1,
        KeyCode::F2 => Scancode::F2,
        KeyCode::F3 => Scancode::F3,
        KeyCode::F4 => Scancode::F4,
        KeyCode::F5 => Scancode::F5,
        KeyCode::F6 => Scancode::F6,
        KeyCode::F7 => Scancode::F7,
        KeyCode::F8 => Scancode::F8,
        KeyCode::F9 => Scancode::F9,
        KeyCode::F10 => Scancode::F10,
        KeyCode::F11 => Scancode::F11,
        KeyCode::F12 => Scancode::F12,

        KeyCode::CapsLock => Scancode::CapsLock,
        KeyCode::PrintScreen => Scancode::PrintScreen,
        KeyCode::ScrollLock => Scancode::ScrollLock,
        KeyCode::Pause => Scancode::Pause,

        _ => return None,
    };

    Some(sc as u16)
}
